// const jobs = [
//   {
//     field: "IT",
//     title: "Web Developer",
//     company: "Farsoft Infotech Private Limited",
//     location: "Mumbai",
//     salary: "5 - 8 LPA",
//   },
//   {
//     field: "Marketing",
//     title: "Advertising Executive",
//     company: "IDZ Digital Private Limited",
//     location: "Thane, Navi Mumbai, Mumbai",
//     salary: "2 - 3 LPA",
//   },
//   {
//     field: "Sales",
//     title: "Sales Operations Executive",
//     company: "IIDE Education Private Limited",
//     location: "Mumbai",
//     salary: "2.4 - 3 LPA",
//   },
//   {
//     field: "Management",
//     title: "Event Management Specialist",
//     company: "MentorBoxx",
//     location: "Pune, Mumbai",
//     salary: "4 - 6 LPA",
//   },
// ];

export const data = [
  {
    id: 1,
    title: "Quality Engineer",
    company: "Thoughtworks",
    location: "Lomboy",
    salary: "$3370.15",
  },
  {
    id: 2,
    title: "Sales Representative",
    company: "Riffpedia",
    location: "Yitang",
    salary: "$5076.85",
  },
  {
    id: 3,
    title: "Database Administrator I",
    company: "Linkbuzz",
    location: "Ol Kalou",
    salary: "$9232.23",
  },
  {
    id: 4,
    title: "GIS Technical Architect",
    company: "Twitterbridge",
    location: "Byerazino",
    salary: "$6491.37",
  },
  {
    id: 5,
    title: "Web Developer IV",
    company: "Zoombeat",
    location: "Xinji",
    salary: "$7302.93",
  },
  {
    id: 6,
    title: "Nuclear Power Engineer",
    company: "Zoomzone",
    location: "Pinsk",
    salary: "$4820.82",
  },
  {
    id: 7,
    title: "Staff Accountant II",
    company: "Twiyo",
    location: "Pingyi",
    salary: "$5867.85",
  },
  {
    id: 8,
    title: "Software Test Engineer II",
    company: "Photobug",
    location: "Kuala Lumpur",
    salary: "$9661.74",
  },
  {
    id: 9,
    title: "Geologist IV",
    company: "Tagfeed",
    location: "Momil",
    salary: "$3483.84",
  },
  {
    id: 10,
    title: "Assistant Manager",
    company: "Browsebug",
    location: "Pucara",
    salary: "$6303.24",
  },
  {
    id: 11,
    title: "Human Resources Assistant I",
    company: "Geba",
    location: "Dongqu",
    salary: "$2488.01",
  },
  {
    id: 12,
    title: "Graphic Designer",
    company: "Youopia",
    location: "Marugame",
    salary: "$2865.80",
  },
  {
    id: 13,
    title: "Internal Auditor",
    company: "Devshare",
    location: "Nedakonice",
    salary: "$2226.76",
  },
  {
    id: 14,
    title: "Analog Circuit Design manager",
    company: "Vinte",
    location: "Bubanza",
    salary: "$2076.34",
  },
  {
    id: 15,
    title: "Accounting Assistant IV",
    company: "Photojam",
    location: "Penalva de Alva",
    salary: "$5118.06",
  },
  {
    id: 16,
    title: "Professor",
    company: "Skiptube",
    location: "Novyy Svit",
    salary: "$5292.18",
  },
  {
    id: 17,
    title: "Tax Accountant",
    company: "Zoombox",
    location: "Mangai",
    salary: "$7453.45",
  },
  {
    id: 18,
    title: "VP Product Management",
    company: "Blogpad",
    location: "Qilin",
    salary: "$9211.78",
  },
  {
    id: 19,
    title: "Health Coach III",
    company: "Plajo",
    location: "Cruzeiro",
    salary: "$6680.91",
  },
  {
    id: 20,
    title: "Quality Engineer",
    company: "Eamia",
    location: "Sŭedinenie",
    salary: "$6987.04",
  },
  {
    id: 21,
    title: "Geologist III",
    company: "Feedfish",
    location: "Qianxu Zhen",
    salary: "$7727.89",
  },
  {
    id: 22,
    title: "Information Systems Manager",
    company: "Fatz",
    location: "Jenesano",
    salary: "$8381.04",
  },
  {
    id: 23,
    title: "Environmental Specialist",
    company: "Realpoint",
    location: "Ferreiras",
    salary: "$7374.94",
  },
  {
    id: 24,
    title: "Editor",
    company: "Ailane",
    location: "Shiyuetian",
    salary: "$4517.15",
  },
  {
    id: 25,
    title: "Marketing Manager",
    company: "Flashspan",
    location: "Hengdong Chengguanzhen",
    salary: "$6954.40",
  },
  {
    id: 26,
    title: "Marketing Manager",
    company: "Youspan",
    location: "Itaperuna",
    salary: "$5555.34",
  },
  {
    id: 27,
    title: "Teacher",
    company: "Centidel",
    location: "Taranovskoye",
    salary: "$3046.20",
  },
  {
    id: 28,
    title: "Senior Developer",
    company: "Dabshots",
    location: "Jinchang",
    salary: "$7110.06",
  },
  {
    id: 29,
    title: "Analyst Programmer",
    company: "Browsedrive",
    location: "Palmas Bellas",
    salary: "$6735.13",
  },
  {
    id: 30,
    title: "Civil Engineer",
    company: "Quimm",
    location: "Khanabad",
    salary: "$5856.59",
  },
  {
    id: 31,
    title: "Graphic Designer",
    company: "Realmix",
    location: "Al Ghayl",
    salary: "$2193.25",
  },
  {
    id: 32,
    title: "Director of Sales",
    company: "Quatz",
    location: "Rongelap",
    salary: "$4271.33",
  },
  {
    id: 33,
    title: "Dental Hygienist",
    company: "Zazio",
    location: "Kayunga",
    salary: "$9988.05",
  },
  {
    id: 34,
    title: "Biostatistician I",
    company: "Miboo",
    location: "Yeoju",
    salary: "$7676.36",
  },
  {
    id: 35,
    title: "Web Developer III",
    company: "Lajo",
    location: "Yunlu",
    salary: "$4717.39",
  },
  {
    id: 36,
    title: "Business Systems Development Analyst",
    company: "Skimia",
    location: "Kavála",
    salary: "$3468.85",
  },
  {
    id: 37,
    title: "Business Systems Development Analyst",
    company: "Thoughtsphere",
    location: "Guanyinsi",
    salary: "$6200.13",
  },
  {
    id: 38,
    title: "Community Outreach Specialist",
    company: "Youfeed",
    location: "Łodygowice",
    salary: "$7748.38",
  },
  {
    id: 39,
    title: "Developer III",
    company: "Yacero",
    location: "Junín",
    salary: "$8569.65",
  },
  {
    id: 40,
    title: "Analog Circuit Design manager",
    company: "Realcube",
    location: "Świnice Warckie",
    salary: "$9026.04",
  },
  {
    id: 41,
    title: "Health Coach IV",
    company: "Npath",
    location: "Alexandria",
    salary: "$6161.72",
  },
  {
    id: 42,
    title: "Software Consultant",
    company: "Meezzy",
    location: "Kanália",
    salary: "$4939.66",
  },
  {
    id: 43,
    title: "Administrative Assistant III",
    company: "Bluezoom",
    location: "Waco",
    salary: "$8246.46",
  },
  {
    id: 44,
    title: "Civil Engineer",
    company: "Teklist",
    location: "Pingdu",
    salary: "$3318.04",
  },
  {
    id: 45,
    title: "Web Developer II",
    company: "Linkbuzz",
    location: "Dayapan",
    salary: "$6870.44",
  },
  {
    id: 46,
    title: "Registered Nurse",
    company: "Skilith",
    location: "Mauhao",
    salary: "$2238.45",
  },
  {
    id: 47,
    title: "Senior Editor",
    company: "Kamba",
    location: "Paraíso de Chabasquén",
    salary: "$3137.72",
  },
  {
    id: 48,
    title: "Speech Pathologist",
    company: "Photolist",
    location: "Pärnu-Jaagupi",
    salary: "$3474.23",
  },
  {
    id: 49,
    title: "Product Engineer",
    company: "Flashpoint",
    location: "Vologda",
    salary: "$8941.17",
  },
  {
    id: 50,
    title: "Assistant Media Planner",
    company: "JumpXS",
    location: "Apače",
    salary: "$7744.66",
  },
  {
    id: 51,
    title: "Food Chemist",
    company: "Gigaclub",
    location: "Labuhanjambu",
    salary: "$6404.82",
  },
  {
    id: 52,
    title: "Office Assistant IV",
    company: "Yodoo",
    location: "Koygorodok",
    salary: "$8143.55",
  },
  {
    id: 53,
    title: "Account Executive",
    company: "Shufflester",
    location: "Tulusmulyo",
    salary: "$7417.43",
  },
  {
    id: 54,
    title: "Dental Hygienist",
    company: "Ainyx",
    location: "Erie",
    salary: "$4935.76",
  },
  {
    id: 55,
    title: "Occupational Therapist",
    company: "Kaymbo",
    location: "Muncar",
    salary: "$2216.84",
  },
  {
    id: 56,
    title: "Compensation Analyst",
    company: "Kimia",
    location: "Dukuhpicung",
    salary: "$5512.42",
  },
  {
    id: 57,
    title: "Paralegal",
    company: "Realcube",
    location: "Cigagade",
    salary: "$4220.40",
  },
  {
    id: 58,
    title: "Executive Secretary",
    company: "Feedspan",
    location: "Jelbuk",
    salary: "$8539.91",
  },
  {
    id: 59,
    title: "Help Desk Technician",
    company: "Skilith",
    location: "Aliaga",
    salary: "$9825.70",
  },
  {
    id: 60,
    title: "Administrative Assistant IV",
    company: "Thoughtstorm",
    location: "Kaédi",
    salary: "$8093.12",
  },
  {
    id: 61,
    title: "Paralegal",
    company: "Pixoboo",
    location: "Sūq Şirwāḩ",
    salary: "$7791.98",
  },
  {
    id: 62,
    title: "Speech Pathologist",
    company: "Linkbuzz",
    location: "Tālīn",
    salary: "$4277.22",
  },
  {
    id: 63,
    title: "Occupational Therapist",
    company: "Devpoint",
    location: "Östhammar",
    salary: "$5044.70",
  },
  {
    id: 64,
    title: "Senior Sales Associate",
    company: "Edgeclub",
    location: "Chunjiang",
    salary: "$9300.76",
  },
  {
    id: 65,
    title: "Assistant Manager",
    company: "Tagfeed",
    location: "Saitama",
    salary: "$5937.12",
  },
  {
    id: 66,
    title: "Compensation Analyst",
    company: "Gigaclub",
    location: "Chengtian",
    salary: "$8139.73",
  },
  {
    id: 67,
    title: "Staff Accountant III",
    company: "Kazu",
    location: "Ciudad Cortés",
    salary: "$7009.38",
  },
  {
    id: 68,
    title: "Accounting Assistant I",
    company: "Livepath",
    location: "Logung",
    salary: "$2712.10",
  },
  {
    id: 69,
    title: "Junior Executive",
    company: "Abata",
    location: "Santa Luzia",
    salary: "$6817.73",
  },
  {
    id: 70,
    title: "Senior Financial Analyst",
    company: "Dabshots",
    location: "Santa Eulalia",
    salary: "$3427.47",
  },
  {
    id: 71,
    title: "Marketing Assistant",
    company: "Wikivu",
    location: "Manzherok",
    salary: "$7581.37",
  },
  {
    id: 72,
    title: "Research Associate",
    company: "Zooxo",
    location: "Verkhnyachka",
    salary: "$6087.52",
  },
  {
    id: 73,
    title: "Civil Engineer",
    company: "Gigaclub",
    location: "Évry",
    salary: "$4534.75",
  },
  {
    id: 74,
    title: "General Manager",
    company: "BlogXS",
    location: "La Loma",
    salary: "$6932.53",
  },
  {
    id: 75,
    title: "Registered Nurse",
    company: "Thoughtsphere",
    location: "Brikama",
    salary: "$5854.28",
  },
  {
    id: 76,
    title: "Financial Advisor",
    company: "Jaxspan",
    location: "Dologon",
    salary: "$9819.02",
  },
  {
    id: 77,
    title: "Software Consultant",
    company: "Feedbug",
    location: "Xialu",
    salary: "$6229.36",
  },
  {
    id: 78,
    title: "Senior Editor",
    company: "Shufflebeat",
    location: "Depok",
    salary: "$8951.28",
  },
  {
    id: 79,
    title: "VP Accounting",
    company: "Lazz",
    location: "L'Île-Perrot",
    salary: "$7368.62",
  },
  {
    id: 80,
    title: "Information Systems Manager",
    company: "Voonyx",
    location: "Göteborg",
    salary: "$8073.50",
  },
  {
    id: 81,
    title: "Analog Circuit Design manager",
    company: "Feedfish",
    location: "Bensonville",
    salary: "$6465.55",
  },
  {
    id: 82,
    title: "Marketing Manager",
    company: "Trilith",
    location: "Villa Lugano",
    salary: "$4622.44",
  },
  {
    id: 83,
    title: "Design Engineer",
    company: "Divanoodle",
    location: "Amieira",
    salary: "$4229.51",
  },
  {
    id: 84,
    title: "Software Engineer II",
    company: "Agivu",
    location: "New Brunswick",
    salary: "$9694.96",
  },
  {
    id: 85,
    title: "Nurse Practicioner",
    company: "Dabjam",
    location: "Ra-ngae",
    salary: "$4080.72",
  },
  {
    id: 86,
    title: "Analog Circuit Design manager",
    company: "Browsecat",
    location: "Bozkow",
    salary: "$4487.73",
  },
  {
    id: 87,
    title: "Engineer III",
    company: "Abatz",
    location: "Laborde",
    salary: "$4010.61",
  },
  {
    id: 88,
    title: "Environmental Specialist",
    company: "Skiba",
    location: "Sumuran",
    salary: "$4289.63",
  },
  {
    id: 89,
    title: "Professor",
    company: "Bluezoom",
    location: "Kebonsari",
    salary: "$4502.41",
  },
  {
    id: 90,
    title: "Web Developer I",
    company: "Edgepulse",
    location: "Pekijing",
    salary: "$8949.49",
  },
  {
    id: 91,
    title: "Business Systems Development Analyst",
    company: "Zoomzone",
    location: "Afogados da Ingazeira",
    salary: "$7956.90",
  },
  {
    id: 92,
    title: "Teacher",
    company: "Kanoodle",
    location: "Kuala Terengganu",
    salary: "$8892.08",
  },
  {
    id: 93,
    title: "Tax Accountant",
    company: "Dabshots",
    location: "Jinsha",
    salary: "$5807.89",
  },
  {
    id: 94,
    title: "Human Resources Assistant II",
    company: "Skipfire",
    location: "Kvitok",
    salary: "$9752.73",
  },
  {
    id: 95,
    title: "Civil Engineer",
    company: "Fanoodle",
    location: "Shimen",
    salary: "$7153.76",
  },
  {
    id: 96,
    title: "Senior Editor",
    company: "Topiczoom",
    location: "Limeil-Brévannes",
    salary: "$8300.41",
  },
  {
    id: 97,
    title: "Information Systems Manager",
    company: "Yotz",
    location: "Cochadas",
    salary: "$2696.06",
  },
  {
    id: 98,
    title: "Engineer III",
    company: "Buzzshare",
    location: "Washington",
    salary: "$9327.93",
  },
  {
    id: 99,
    title: "Paralegal",
    company: "Quinu",
    location: "Beishan",
    salary: "$4668.13",
  },
  {
    id: 100,
    title: "Marketing Manager",
    company: "Meeveo",
    location: "Pailiao",
    salary: "$2615.42",
  },
];
